### ISSUE TITLE
Permission for `create` action does not work

### ISSUE THREAD

**Issue by id3er0** [betterobjects/activeql#3]
Permission for `create` action does not work. Tried both YML and `DomainConfiguration` definition.

A project to reproduce this issue:
https://github.com/id3er0/activeql-example

Permissions definition:
https://github.com/id3er0/activeql-example/blob/master/express/activeql/domain-configuration/car.yml#L15

```
entity:
  Car:
    attributes:
      licence: Key
      brand: CarBrand!
      color: String
      mileage: Int
    permissions:
      admin:
        read: true
        create: true
        update: true
        delete: true
```

Run mutation with Bearer token from `admin` user:

```
mutation {
  createCar (
    car: {
      licence: "002"
      color: "red"
      brand: AUDI
    }
  ) {
    car {
      id
      licence
      color
      brand
    }
  }
}
```

Get this error:

```
{
  "errors": [
    {
      "message": "principal not allowed to create new item of 'Car'",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createCar"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: principal not allowed to create new item of 'Transaction'",
            "    at DefaultEntityPermissions.<anonymous> (/Users/x/dev/activeql-starter/express/node_modules/activeql-server/entities/entity-permissions.ts:86:39)",
            "    at step (/Users/x/dev/activeql-starter/express/node_modules/activeql-server/dist/entities/entity-permissions.js:46:23)",
            "    at Object.next (/Users/x/dev/activeql-starter/express/node_modules/activeql-server/dist/entities/entity-permissions.js:27:53)",
            "    at fulfilled (/Users/x/dev/activeql-starter/express/node_modules/activeql-server/dist/entities/entity-permissions.js:18:58)",
            "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
          ]
        }
      }
    }
  ],
  "data": {
    "createCar": null
  }
}
```

However `read` permission works:

```
query {
  cars (sort: licence_ASC) {
    id
    licence
  }
}
```
